### ISSUE TITLE
Error in event handler for webNavigation.onCreatedNavigationTarget: ReferenceError: defaultMatcher is not defined

### ISSUE THREAD

**Issue by ddsol** [EFForg/privacybadgerchrome#857]
[This code](https://github.com/EFForg/privacybadgerchrome/blob/master/lib/popupBlocker.js#L59) seems to reference something that doesn't exist which generates massive errors.

```
extensions::uncaught_exception_handler:8
Error in event handler for tabs.onUpdated: ReferenceError: defaultMatcher is not defined
    at checkPotentialPopup (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/lib/popupBlocker.js:59:31)
    at chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/lib/popupBlocker.js:47:7
```

**Comment by cooperq** [comment]
this will be fixed in the next release.
