### ISSUE TITLE
PB isn't blocking anything

### ISSUE THREAD

**Issue by lucaspetter** [EFForg/privacybadgerchrome#889]
On Chrome OS (52.0.2743.116), Privacy Badger **isn't blocking anything at all**. (*Edit: the issue is also on OS X*) For example, when I go to [nytimes.com](http://www.nytimes.com/), Privacy Badger's interface says that everything "doesn't seem to be tracking you," including notorious trackers like Chartbeat, NewRelic, Scorecard, and Google Analytics -- the long list of trackers is all green/allowed.

The only other extension installed is HTTPS Everywhere, but the issue is still present with that disabled. I also tried hard-resetting the Chromebook and then reinstalling just PB, but the issue is still there.

Below are the entire contents of the background page console. The problem might be with these 2 lines, but I don't know what they mean:

```
compat.js:77 Error: No data in the file(…)reportError @ compat.js:77
compat.js:78 console.trace()reportError @ compat.js:78
```

```
socialwidgetloader.js:78 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
storage.js:57 loading badgers into the pen
background.js:131 privacy badger is ready to rock
background.js:132 set pb.DEBUG=1 to view console messages
compat.js:77 Error: No data in the file(…)reportError @ compat.js:77
compat.js:78 console.trace()reportError @ compat.js:78
migrations.js:31 changing privacy settings
2https://static01.nyt.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
2https://a1.nyt.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://int.nyt.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 403 (Forbidden)
https://cdn.optimizely.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 403 (Forbidden)
https://int.nyt.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 403 (Forbidden)
https://typeface.nyt.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.googletagservices.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 ()
https://3338050995.log.optimizely.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://cdn3.optimizely.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 403 (Forbidden)
https://partner.googleadservices.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 ()
https://tpc.googlesyndication.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 ()
https://securepubads.g.doubleclick.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 ()
https://js-agent.newrelic.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 403 (Forbidden)
https://s1.nyt.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 403 (Forbidden)
https://z.moatads.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 403 (Forbidden)
https://pagead2.googlesyndication.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 ()
https://cdn.krxd.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
2https://bam.nr-data.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 400 (Bad Request)
https://csi.gstatic.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 ()
https://scontent.xx.fbcdn.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 502 ()
https://ichef.bbci.co.uk/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://a248.e.akamai.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 400 (Bad Request)
https://sb.scorecardresearch.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://contextual.media.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.google-analytics.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 ()
https://st.dynamicyield.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://dc8xl0ndzn2cb.cloudfront.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 403 (Forbidden)
https://st.dynamicyield.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://secure-us.imrworldwide.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://optimizedby.brealtime.com/.well-known/dnt-policy.txt Failed to load resource: net::ERR_INSECURE_RESPONSE
https://medianet-d.openx.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Object Not Found)
https://pnytimes.chartbeat.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
6https://www.facebook.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 ()
https://qsearch-a.akamaihd.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
2https://www.facebook.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 ()
https://qsearch-a.akamaihd.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
2https://www.facebook.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 ()
https://3951336.fls.doubleclick.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 ()
2https://www.facebook.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 ()
https://static.dynamicyield.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://3951336.fls.doubleclick.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 ()
https://static.dynamicyield.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://ckm-m.xp1.ru4.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not found)
https://3951336.fls.doubleclick.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 ()
3https://beacon.krxd.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://apiservices.krxd.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
2https://ib.adnxs.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://kr.ixiaa.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://sync.tidaltv.com/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
https://adadvisor.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
2https://u.openx.net/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Object Not Found)
2https://p2.keywee.co/.well-known/dnt-policy.txt Failed to load resource: the server responded with a status of 404 (Not Found)
migrations.js:149 MIGRATING BLOCKED SUBDOMAINS THAT ARE ON COOKIE BLOCK LIST
utils.js:128 GET https://googleads.g.doubleclick.net/.well-known/dnt-policy.txt 404 ()xhrRequest @ utils.js:128checkPrivacyBadgerPolicy @ background.js:355checkForDNTPolicy @ background.js:331(anonymous function) @ heuristicblocking.js:448

**Comment by cooperq** [comment]
Do you happen to have third party cookies disabled? Can you make a separate chrome profile and install privacy badger there?

**Comment by lucaspetter** [comment]
I've already tried [resetting](https://support.google.com/chrome/answer/6386691) my Chrome sync data and then [Powerwashing](https://support.google.com/chromebook/answer/183084) the Chromebook (basically re-installing Chrome OS) in order to test this with a clean, default Chrome profile. No settings changes, no other extensions, third-party cookies are left enabled by default, etc. Then I installed PB and went to [nytimes.com](http://www.nytimes.com/). But the issue was still there.

Today, I did more testing and found *the same issue exists on OS X* (10.11.6). So it's not just Chrome OS. I used a clean install of Chrome on a Mac that has never had Chrome before. I didn't log in to Chrome. Below are the steps I took:

1. Download Chrome, install it in the Applications folder, run it.
2. Go directly to the [Chrome Web Store](https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp) and install Privacy Badger.
3. Go to [nytimes.com](http://www.nytimes.com/).
4. Click on the PB toolbar icon. Every single tracker is green/allowed, like in the screenshot below.

If I uninstall Chrome from OS X (by deleting all its files from ~/Library) and try again, the issue is reproducible.

![pb-screenshot](https://cloud.githubusercontent.com/assets/13027535/17611924/81bb2eec-6000-11e6-8b49-0b80a44a9549.jpg)

**Comment by lucaspetter** [comment]
On OS X, the background page for PB contains the same errors that I saw earlier on Chrome OS:

```
compat.js:77 Error: No data in the file(…)reportError @ compat.js:77
compat.js:78 console.trace()reportError @ compat.js:78
```

When I click on the `(...)` in the 1st line, it shows more info. The info is the same on OS X and Chrome OS:

```
compat.js:77 Error: No data in the file
    at Object.<anonymous> (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/lib/adblockplus.js:1533:17)
    at Object.readFromFile (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/lib/io.js:59:9)
    at Object.<anonymous> (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/lib/adblockplus.js:1529:12)
    at Object.<anonymous> (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/lib/adblockplus.js:1614:9)
    at callback (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/lib/adblockplus.js:1633:11)reportError @ compat.js:77
compat.js:78 console.trace()reportError @ compat.js:78
migrations.js:31 changing privacy settings
```

**Comment by cowlicks** [comment]
Hi @lucaspetter, does this still happen after you visit several sites?

Privacy badger has to see trackers across several sites before it can classify them. So on a fresh install, it won't initially recognize a tracker on your first visit to a page.

**Comment by lucaspetter** [comment]
@cowlicks You're right! I didn't realize that's how Privacy Badger works. Now that I've tried browsing around several sites with it, the trackers are gradually starting to be blocked. Thank you for pointing that out!
